#!/bin/bash
# primitive script to display some rice info
 
hostname=$(hostname)
username=$(id -un)
distro="Lubuntu 15.10"
processor="AMD 64"
kernel=$(uname -r -s)
font="Tewi"
uptime=$(uptime -p)
wm="herbstluftwm"
terminal="URxvt"
 
echo ""
echo -e '                         ' "\e[34m$username\e[0m@\e[94m$hostname\e[0m"
echo -e '　 　   __,,,,,,__   '
echo -e '　　　(:(　　　　 )　    ' "\e[33m$uptime\e[0m"
echo -e '　　　 |:| ●レ ● |  '
echo -e '　　　 |:|　 つ  |　     ' "\e[31mDistro:\e[0m $distro"
echo -e '　　　 |:|　 　  |　     ' "\e[31mKernel:\e[0m $kernel"
echo -e '        ￣￣￣￣￣       ' "\e[31mFont:\e[0m $font"
echo -e '                         ' "\e[31mTerminal:\e[0m $terminal"
echo -e '                         ' "\e[31mWM:\e[0m $wm"
echo ""
